baseURL = 'https://neur0nz.github.io/CafeBaBoker/'
languageCode = 'en-us'
title = 'Cafe BaBoker'
theme = 'PaperMod'

# Enable search index generation
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Enable math rendering
[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = true
  ShowAuthor = true
  ShowAuthorAvatar = true
  ShowAuthorBio = true
  ShowAuthorSocial = true
  ShowAuthorLinks = true
  ShowToc = true
  [params.assets]
    favicon = "/CafeBaBoker/favicon.ico"
    favicon16x16 = "/CafeBaBoker/favicon-16x16.png"
    favicon32x32 = "/CafeBaBoker/favicon-32x32.png"
    apple_touch_icon = "/CafeBaBoker/apple-touch-icon.png"
    safari_pinned_tab = "/CafeBaBoker/safari-pinned-tab.svg"
  [params.math]
    enable = true
    katex = true
    mathjax = false
    katexVersion = "0.16.9"
    katexCDN = "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist"
  [params.search]
    enable = true
    type = "fuse"
    content = true
    placeholder = "Search through posts..."
    maxResultLength = 10
    snippetLength = 100
    highlightTag = "em"
    fuzzy = true
    showEmptySections = true
    showResults = true
    showNoResults = true
    defaultContent = true
    [params.search.fuse]
      isCaseSensitive = false
      shouldSort = true
      location = 0
      distance = 100
      threshold = 0.4
      minMatchCharLength = 1

# Math rendering settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    lineNoStart = 1
    lineNumbersInTable = true
    style = "monokai"
    tabWidth = 4

# Image handling
[imaging]
  quality = 75
  resampleFilter = "Lanczos"
  anchor = "Smart"

[params.profileMode]
  enabled = true
  title = "Cafe BaBoker"
  subtitle = "\"A mathematician is a machine for turning coffee into theorems.\" - Alfréd Rényi"
  imageUrl = "images/coffee-beans.jpg"
  imageTitle = "Coffee Beans"
  imageLink = "https://github.com/neur0nz"
  buttons = [
    { name = "Posts", url = "/CafeBaBoker/posts" },
    { name = "Archive", url = "/CafeBaBoker/archive" }
  ]

[params.homeInfoParams]
  Title = "About Cafe BaBoker"
  Content = """
  Cafe BaBoker (קפה בבוקר) is a collaborative blog where we explore and discuss topics that interest us in:
  * Mathematics
  * Computer Science
  * Physics
  * Other subjects that spark our intellectual curiosity

  ## Contact
  If you'd like to write a guest post or have a suggestion, feel free to reach out to me at [nadavprr@gmail.com](mailto:nadavprr@gmail.com) or connect on [GitHub](https://github.com/neur0nz).
  """

# Giscus Comments Configuration
[params.comments]
  enabled = true
  provider = "giscus"
  [params.comments.giscus]
    repo = "Neur0nz/CafeBaBoker"
    repoId = "R_kgDOOOUhRA"
    category = "Announcements"
    categoryId = "DIC_kwDOOOUhRM4Cocfc"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "0"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "transparent_dark"
    lang = "en"
    loading = "lazy"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -90
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = -88
  [[menu.main]]
    identifier = "authors"
    name = "Authors"
    url = "/authors/"
    weight = -85
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = -75
