baseURL = 'https://neur0nz.github.io/NPBlog/'
languageCode = 'en-us'
title = 'Cafe BaBoker'
theme = 'PaperMod'

# Enable math rendering
[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  ShowAuthor = true
  ShowAuthorAvatar = true
  ShowAuthorBio = true
  ShowAuthorSocial = true
  ShowAuthorLinks = true
  ShowToc = true
  [params.assets]
    favicon = "/NPBlog/favicon.ico"
    favicon16x16 = "/NPBlog/favicon-16x16.png"
    favicon32x32 = "/NPBlog/favicon-32x32.png"
    apple_touch_icon = "/NPBlog/apple-touch-icon.png"
    safari_pinned_tab = "/NPBlog/safari-pinned-tab.svg"
  [params.math]
    enable = true
    katex = true
    mathjax = false
    katexVersion = "0.16.9"
    katexCDN = "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist"

# Math rendering settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    lineNoStart = 1
    lineNumbersInTable = true
    style = "monokai"
    tabWidth = 4

# Image handling
[imaging]
  quality = 75
  resampleFilter = "Lanczos"
  anchor = "Smart"

[params.homeInfoParams]
  Title = "Welcome to My Mathematics Blog 👋"
  Content = "Exploring the beauty of mathematics through articles, proofs, and visualizations."

[params.profileMode]
  enabled = true
  title = "Cafe BaBoker"
  subtitle = "\"A mathematician is a machine for turning coffee into theorems.\" - Alfréd Rényi"
  imageUrl = "images/coffee-beans.jpg"
  imageTitle = "Coffee Beans"
  imageLink = "https://github.com/neur0nz"

# Giscus Comments Configuration
[params.comments]
  enabled = true
  provider = "giscus"
  [params.comments.giscus]
    repo = "Neur0nz/NPBlog"
    repoId = "R_kgDOOOUhRA"
    category = "Announcements"
    categoryId = "DIC_kwDOOOUhRM4Cocfc"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "0"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "preferred_color_scheme"
    lang = "en"
    loading = "lazy"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -90
  [[menu.main]]
    identifier = "authors"
    name = "Authors"
    url = "/authors/"
    weight = -85
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -80
